# Generated by Django 4.2.17 on 2024-12-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'teaspoon'), ('tsps', 'teaspoons'), ('tbsp', 'tablespoon'), ('tbsps', 'tablespoons'), ('fl oz', 'fluid ounce'), ('cup', 'cup'), ('cups', 'cups'), ('g', 'grams'), ('kg', 'kilograms'), ('l', 'liters'), ('ml', 'milliters'), ('cm', 'centimeters'), (' ', ' ')], default='g', max_length=20),
        ),
    ]
