# Generated by Django 4.2.17 on 2025-01-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(default='Recipe Comment', max_length=50),
        ),
    ]
