# Generated by Django 4.2.17 on 2025-01-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_comment_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='other_ingredients',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
