# Generated by Django 4.2.17 on 2025-01-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_other_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='other_ingredients',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
